#vim:set nobomb:set encoding=utf-8
########################################
#	Brief	ddc.vim plugins
#	Author	KORYUOH
#	Create	2024/08/26
#	Update	2024/10/09
#	Version	1.14
#	Lazy : Not Lazy
########################################

[[plugins]]
#from neocomplete -> ddc.vim
repo = 'Shougo/ddc.vim'
depends=['denops.vim']
hook_add='''
let s:hook_name = g:vimrc_folder.'/'.'ddc_setting.vim'
execute 'source '.s:hook_name
'''

## ===== DDC Sources

[[plugins]]
repo = 'Shougo/ddc-ui-native'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'Shougo/ddc-around'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'shun/ddc-source-vim-lsp'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'matsui54/ddc-source-buffer'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'tani/ddc-fuzzy'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'delphinus/ddc-ctags'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops.vim']

[[plugins]]
repo = 'yasunori0418/statusline_skk.vim'
on_source = ['skkeleton']


# [[plugins]]
# repo = 'Shougo/ddc-source-nextword'
# " -> NextWord
# " \		'nextword' : {
# " \				'mark' : '[NextWord]',
# " \				'minAutoCompleteLength' : 3,
# " \				'isVolatile' : v:true,
# " \				'matchers' : ['matcher_head'],
# " \				'sorters' : ['sorter_rank'],
# " \			},
	

## ===== DDC Sources
