#vim:set nobomb:set encoding=utf-8
########################################
#	Brief	ddc.vim plugins
#	Author	KORYUOH
#	Create	2024/08/26
#	Update	2024/08/29
#	Version	1.11
#	Lazy : Not Lazy
########################################

[[plugins]]
#from neocomplete -> ddc.vim
repo = 'Shougo/ddc.vim'
depends=['denops.vim']
hook_add='''
call ddc#custom#patch_global({
\	'ui': 'native',
\	'sources' :[
\		'vim-lsp',
\		'around',
\		'buffer',
\		'neosnippet',
\		'file',
\		'look',
\		],
\	'sourceOptions': {
\		'_': {
\			'matchers'  : ['matcher_fuzzy'],
\			'sorters'   : ['sorter_fuzzy'],
\			'converters': ['converter_fuzzy'],
\			'ignoreCase': v:true,
\		},
\		'around': {
\			'mark': '[Arround]',
\		},
\		'buffer': {
\			'mark': '[Buffer]',
\		},
\		'vim-lsp': {
\			'mark': '[LSP]',
\			'forceCompletionPattern': '\.\w*|:\w*|->\w*',
\		},
\		'neosnippet' : {
\				'mark' : '[NS]',
\				},
\		},
\		'file' : {
\			'mark' : '[file]',
\			'isVolatile' : v:true,
\			'forceCompletionPattern':'\S/\S*',
\		},
\		'look' : {
\			'matchers' : [],
\			'converters' : ['loud','matcher_head'],
\			'mark' : '[look]',
\			"isVolatile" : v:true,
\		},
\	'sourceParams': {
\		'around': { 'maxSize': 500 },
\		'file' : {
\				'mode' : 'win32',
\			},
\		'buffer': {
\			'limitBytes': 5000000,
\			'forceCollect': v:true,
\			'fromAltBuf': v:true,
\		},
\		'look' : {
\			'convertCase' : v:true,
\			'dict' : v:null,
\		}
\	 },
\})

" Tab Complete
inoremap <expr> <TAB>
\pumvisible() ? '<C-n>' : 
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ? 
\ '<TAB>' : ddc#map#ddc#map#manual_complete()

"Shift-Tab completion back
inoremap <expr> <S-TAB> pumvisible() ? '<C-p>' : '<C-h>'

call ddc#enable()
'''

## ===== DDC Sources

[[plugins]]
repo = 'Shougo/ddc-ui-native'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'Shougo/ddc-around'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'shun/ddc-source-vim-lsp'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'matsui54/ddc-source-buffer'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'octaltree/cmp-look'
depends = ['denops.vim' , 'ddc.vm']

[[plugins]]
repo = 'tani/ddc-fuzzy'
depends = ['denops.vim' , 'ddc.vm']

# [[plugins]]
# repo = 'Shougo/ddc-source-nextword'
# " -> NextWord
# " \		'nextword' : {
# " \				'mark' : '[NextWord]',
# " \				'minAutoCompleteLength' : 3,
# " \				'isVolatile' : v:true,
# " \				'matchers' : ['matcher_head'],
# " \				'sorters' : ['sorter_rank'],
# " \			},
	

## ===== DDC Sources
