#vim:set nobomb:set encoding=utf-8
########################################
#	Brief	dein Plugins
#	Author	KORYUOH
#	Create	
#	Update	2017/05/03
#	Version	1.00
########################################

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = [ 'context_filetype.vim' ]

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
augroup SetColorScheme 
	au!
	au VimEnter * nested colorscheme molokai
augroup END
	'''

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
	nmap <leader>f :Unite file -buffer-name=UniteFiler<CR>
	nmap <leader>F :Unite file:**/*.{cpp,h} -buffer-name=UniteFiler<CR>
	nmap <leader>vg :Unite vimgrep -buffer-name=UniteQuickFix<CR>
	nmap <leader>cw :UniteResume -buffer-name=UniteQuickFix<CR>
	nmap <leader>co :UniteResume UniteOutLiner<CR>
	nmap <leader>ul :Unite line -buffer-name=UniteOutLiner<CR>
	nmap <leader>ut :Unite tab -buffer-name=UniteOutLiner<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
hook_add = '''
	nmap <leader>mf :Unite file_mru -buffer-name=UniteFiler<CR>
'''

[[plugins]]
repo = 'Shougo/unite-outline'
hook_add = '''
nmap <C-W>u :Unite outline:! -buffer-name=UniteOutLiner<CR>
'''

[[plugins]]
repo = 'sgur/unite-qf'
hook_add='''
	nmap <leader>ucw :Unite qf -buffer-name=UniteQuickFix<CR>
'''

[[plugins]]
repo = 'koron/codic-vim'

[[plugins]]
repo = 'rhysd/unite-codic.vim'
hook_add = '''
	nmap <leader>uc :Unite codic<CR>
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'AndrewRadev/switch.vim'
hook_add = '''
let g:switch_mapping = "-"
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'mattn/flappyvird-vim'

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
	if isdirectory(expand("~/.memolist"))
		let g:memolist_path = expand("~/.memolist")
	endif
	
	let g:memolist_unite        = 1
	let g:memolist_unite_source = "file"
	let g:memolist_unite_option = "-auto-preview -start-insert"
	function! s:UniteMemoList()
		let l:memolist_path = unite#util#path2directory(g:memolist_path)
		call unite#start([['file_rec',l:memolist_path ]])
	endfunction

	command! UniteMemoList call s:UniteMemoList()
	nmap <leader>mn :MemoNew<CR>
	nmap <leader>ml :MemoList<CR>
	nmap <leader>mg :MemoGrep<CR>
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'mattn/invader-vim'   

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add='''
let g:indent_guides_enable_on_vim_startup = 1
'''


