#vim:set nobomb:set encoding=utf-8
########################################
#	Brief	dein Plugins
#	Author	KORYUOH
#	Create	2017/10/16
#	Update	2017/10/16
#	Version	1.00
#	Lazy : Lazy
########################################


