#vim:set nobomb:set encoding=utf-8
########################################
#	Brief	dein Plugins
#	Author	KORYUOH
#	Create	2017/10/16
#	Update	2018/05/09
#	Version	1.02
#	Lazy : Lazy
########################################

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = 'php'
