#vim:set nobomb:set encoding=utf-8
########################################
#	Brief	dein Plugins
#	Author	KORYUOH
#	Create	2017/10/16
#	Update	2024/11/02
#	Version	1.11
#	Lazy : Lazy
########################################

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = 'php'

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['blade','html' , 'xml' ]
hook_add = '''
let g:closetag_filetypes = 'html,xml,blade,xhtml'
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
hook_add = '''
autocmd FileType vue syntax sync fromstart
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'vim-scripts/confluencewiki.vim'
on_ft= 'confluencewiki' 


[[plugins]]
repo = 'vim-syntastic/syntastic.git'
on_ft='php'
hook_add = '''
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntasitic_check_on_wq = 0
let g:synstatic_enable_signs = 1
let g:systastic_echo_current_error = 1
let g:syntastic_enable_higilighting = 1
" see :h syntasitic-loclist-callback
function! SyntasticCheckHook(errors)
	if !empty(a:errors)
		let g:syntastic_loc_list_height = min([len(a:errors) , 5])
	endif
endfunction
'''
