#vim:set nobomb:set encoding=utf-8
########################################
#	Brief	dein Plugins
#	Author	KORYUOH
#	Create	2017/10/16
#	Update	2018/09/04
#	Version	1.10
#	Lazy : Lazy
########################################

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = 'php'

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['blade','html' , 'xml' ]
hook_add = '''
let g:closetag_filetypes = 'html,xml,blade,xhtml'
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
hook_add = '''
autocmd FileType vue syntax sync fromstart
'''
