#vim:set nobomb:set encoding=utf-8
########################################
#	Brief	dein Plugins
#	Author	KORYUOH
#	Create	2017/10/16
#	Update	2018/06/08
#	Version	1.07
#	Lazy : Lazy
########################################

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = 'php'

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = 'blade'
hook_add = '''
let g:closetag_filetypes = 'html,xml,blade,xhtml'
'''
